openapi: 3.0.0
info:
  title: Seamless
  version: '1.0'
  contact:
    name: Eyecu.Digital
  description: |-
    ## Presentation of the Seamless

    In this article we will see how the seamless flow is working.

    You will have to give us an endpoint from your system (GET Endpoint). This endpoint need to be always available, otherwise the games will not work.

    Let's take an example, as your endpoint will be : https://www.casino.pro/seamless


    ### Events list
    <!-- title: Events list -->

    | Event Name |      Require answer |   Description |
    | ------------- | :-----------: | -----: |
    | getBalance      | YES | Retrive the balance of the user |
    | updateBalance      |   NO |   Update the balance of the user |
    | gameStats |   NO    |   Send a round statistic (bet, win, profit etc) |
    | gameLog |   NO    |   Send a log of the game played (game id, user id, ip etc) |
    | jackpotUpdate |   NO    |  Send a jackpot update for the player |
    | gameError |   NO    |   Send an error log if the game have any problem |
servers:
  - url: 'https://games.eyecu.digital'
    description: EyeCu Games Servers
paths:
  '/launcher/{game}/{token}/{mode}':
    parameters:
      - schema:
          type: string
          example: CorridaRomanceWD
        name: game
        in: path
        required: true
        description: Game name
      - schema:
          type: string
          example: Hf4h08gf87e8z70ef8zf7ze89f
        name: token
        in: path
        required: true
        description: Seamless token
      - schema:
          type: string
          example: desktop
        name: mode
        in: path
        required: true
        description: Game mode (desktop or mobile)
    get:
      summary: Start a game session for the user
      tags:
        - Game session
      responses:
        '307':
          description: |-
            Temporary Redirect

            Redirect automaticly to the game
      operationId: get-launcher-game-token-mode
      description: |-
        This is not an API endpoint ! You should redirect the user (or serve it in an iframe) using this syntax.

        https://games.eyecu.digital/launcher/{game}/{token}/{mode}

        Games name = from /api/games => use the 'name' property of the game (not the title)

        Token = Check 'Seamless token generation' to see how to generate it

        Mode = desktop or mobile

        ### /!\ Information for the lobby url /!\
        You can add the lobby url with : ?lobby_url={lobby_url} at the end

        For exemple :

        /launcher/NarcosNET/JWT_TOKEN/desktop?lobby_url=https://www.google.com (You need to write the full url with https://, http://)

        If you don't provide the lobby url, it will take by default the lobby_url enter in your shop admin configuration (default lobby url).

        If you pass the lobby url in the api when you start a game, it will prioritize it.
  /event/getBalance:
    get:
      summary: getBalance
      tags:
        - Events
      responses:
        '200':
          description: OK
      operationId: get-event-getBalance
      description: |-
        <!-- theme: info -->
        > #### This is not an endpoint

        This event is used to get the current balance of the user, this event is called inside the games in the next events:

        When the game is started

        Every 5 seconds (depend's on the game)

        Before a spin

        After a spin

        Request example to your seamless api :

        https://www.casino.pro/seamless?shop_id=1&user_id=1&event=getBalance&request_time=1598347737744

        | Param |      Description |
        | ------------- | :-----------: | -----: |
        | shop_id | Your Shop ID |
        | user_id |  Your User ID |
        | event |  getBalance |
        | request_time |  UNIX Timestamp (ms) when the request has been sent |

        This request expects a JSON response.

        | Param | Type | Example | Description
        | -------- | --------- | ------- | ------- |
        | user_id | STRING | "1" | User ID of the asked balance |
        | balance | FLOAT | 125.25 | Amount of the user balance |

        Example :

        \```json
        {
          "user_id": "1",
          "balance": 125.25
        }
        \```
components:
  schemas: {}
tags:
  - name: Events
