openapi: 3.0.0
info:
  title: Users
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/login:
    post:
      summary: User authentication
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
              examples:
                Login success:
                  value:
                    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vdGVzdGluZy5sdWNreS1zdHJpa2UuY2x1Yi9hcGkvbG9naW4iLCJpYXQiOjE1OTY1MzcwNDQsImV4cCI6MTU5NjU0MDY0NCwibmJmIjoxNTk2NTM3MDQ0LCJqdGkiOiIyS0V2RXVMckM3bTY2aW9VSURvME1kdEtHckkxT3FmaTBXdVJwOHVWIiwic3ViIjo2NywicHJ2IjoiM2VmNmNmODlmNTU5YTkyYjNlYjdiNzdiOGM3MmRiMzlkNDdlZGI2MCJ9.XaTpLVWTJaSCfT93I8AKACdMGNfGAjAyu3oAHFyoVW4
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                Invalid credentials:
                  value:
                    error: Invalid credentials.
      operationId: post-api-login
      description: Authentication of a user in a Shop
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
            examples: {}
        description: |-
          Authentication request require only 2 parameters : 
          - username : username of the user
          - password : password of the user
      parameters:
        - schema:
            type: string
          in: query
          name: key
          description: API Key of the shop
          required: true
        - schema:
            type: string
          in: query
          name: shop_id
          description: Shop ID
          required: true
      tags:
        - Session
    parameters: []
  /api/me:
    get:
      summary: Get user information
      responses:
        '200':
          description: User fetch success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  first_name:
                    type: string
                  last_name:
                    type: string
                  phone:
                    type: string
                  balance:
                    type: string
                  avatar:
                    type: string
                  address:
                    type: string
                  country_id:
                    type: integer
                  role_id:
                    type: integer
                  status:
                    type: string
                  birthday:
                    type: string
                  last_login:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
              examples:
                User informations:
                  value:
                    id: 67
                    first_name: 'null'
                    last_name: 'null'
                    username: '570358599'
                    phone: 'null'
                    balance: '200.0000'
                    avatar: 'http://website.com/back/img/profile.png'
                    address: 'null'
                    country_id: 1
                    role_id: 1
                    status: Active
                    birthday: 'null'
                    last_login: ''
                    created_at: '2020-08-02 14:21:15'
                    updated_at: '2020-08-02 14:21:15'
        '401':
          description: Unauthorized
      operationId: get-api-me
      description: Get the user information of a logged users (after login success)
      parameters:
        - schema:
            type: string
          in: query
          name: key
          description: API Key of the Shop
          required: true
        - schema:
            type: string
          in: query
          name: shop_id
          description: Shop ID
          required: true
        - schema:
            type: string
          in: header
          name: 'Authorization: Bearer'
          required: true
          description: User Token (provided by /api/login)
      tags:
        - Session
    parameters: []
  /api/me/details:
    get:
      summary: Your GET endpoint
      tags:
        - Session
      responses: {}
      operationId: get-api-me-details
  /api/me/details/auth:
    get:
      summary: Your GET endpoint
      tags:
        - Session
      responses: {}
      operationId: get-api-me-details-auth
  /api/me/avatar:
    put:
      summary: ''
      operationId: put-api-me-avatar
      responses:
        '200':
          description: OK
      tags:
        - Session
    delete:
      summary: ''
      operationId: delete-api-me-avatar
      responses:
        '200':
          description: OK
  /me/avatar/external:
    put:
      summary: Your PUT endpoint
      tags:
        - Session
      responses: {}
      operationId: put-me-avatar-external
  /api/me/sessions:
    get:
      summary: Your GET endpoint
      tags:
        - Session
      responses: {}
      operationId: get-api-me-sessions
  /api/me/return:
    get:
      summary: Your GET endpoint
      tags:
        - Session
      responses: {}
      operationId: get-api-me-return
components:
  schemas: {}
tags:
  - name: Session
